stages:
  - build
  - test

variables:
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"

build_images:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t app-flask -f docker/Dockerfile .
    - docker run -d --name flask-app -p 5000:5000 app-flask

test_application:
  stage: test
  image: python:3.10-alpine
  services:
    - docker:dind
  variables:
    KEYCLOAK_URL: "http://keycloak:8080/realms/master/protocol/openid-connect/token"
    FLASK_APP_URL: "http://flask-app:5000"
  before_script:
    - apk add --no-cache python3 py3-pip curl
    - python3 -m venv venv
    - . venv/bin/activate
    - pip install --no-cache-dir -r requirements.txt
  script:
    - . venv/bin/activate
    - echo "Rodando testes..."
    - python test_app.py
